### ISSUE TITLE
Support expressions

### ISSUE THREAD

**Issue by hwbllmnn** [geostyler/geostyler#1072]
### Description:

The parsers should be enhanced to support filter expressions.

- [ ] OpenLayers
- [x] SLD
- [ ] Mapbox
- [ ] QGIS

See terrestris/geostyler-style#123

**Comment by jansule** [comment]
Please remove `GeoJson` and `WFS` from the list as they aren't style parsers.
Please also add `Qgis` to the list.

**Comment by dnlkoch** [comment]
See e.g. [here](https://github.com/geostyler/geostyler/pull/1479).

**Comment by KaiVolland** [comment]
The geostyler-style can now handle expressions. The work has to be done in the seperate parsers. I'll close this issue. Feel free to open an issue at the repository of the corresponding parser.
