### ISSUE TITLE
Drag and Drop support for rule re-ordering

### ISSUE THREAD

**Issue by chrismayer** [geostyler/geostyler#1144]
## FEATUREREQUEST
With #1142 the user is allowed to re-order the rules in the `RuleTable` by up-/down-buttons.
Supporting drag and drop for the rule rows would be another or additional mechanism to re-order the rules (suggested by @jansule here https://github.com/terrestris/geostyler/pull/1142#issuecomment-513776915).

See [antd's draggable table rows](https://ant.design/components/table/#components-table-demo-drag-sorting) for more technical information.

**Comment by marcjansen** [comment]
Would it even make sense to select some rows and drag them all? 🤔
