### ISSUE TITLE
Re-order Symbolizers

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler#1145]
### Description:

Along with #1142, #1141 and #1144 it would be nice being able to re-order symbolizers as well.
Antd now also supports [dragging tabs](https://ant.design/components/tabs/#components-tabs-demo-custom-tab-bar-node).

**Comment by marcjansen** [comment]
Thanks for creating the issue for this idea I threw over the fence.

**Comment by chrismayer** [comment]
Absolutely seconding this. Just created some SLDs with the GeoStyler UI and a reordering of symbolizers would be powerful enhancement.

**Comment by KaiVolland** [comment]
Reordering is possible in the demo so i close this.

**Comment by jansule** [comment]
@KaiVolland Are you sure? I just tested and reordering of rules works, whereas reordering of symbolizers does not.
