### ISSUE TITLE
Missing Examples for Components in Documentation

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler#1172]
### Description:
Several components are missing in the documentation and should be added.
See https://terrestris.github.io/geostyler/latest/index.html

WIP Missing  components:

- [x] RuleTable
- [x] Style
- [ ] CodeEditor
- [ ] FieldSet
- [ ] Filter
- [ ] BoolFilterField
- [ ] ComparisonFilter
- [ ] FilterEditorWindow
- [ ] FilterTree
- [ ] NumberFilterField
- [ ] OperatorCombo
- [ ] TextFilterField
- [ ] NameField
- [ ] Rule -> RemoveButton
- [ ] Rule
- [ ] TitleField
- [ ] ClassificationCombo
- [ ] ColorRampCombo
- [ ] ColorSpaceCombo
- [ ] ColorsPreview
- [ ] RuleGeneratorWindow
- [ ] RuleReorderButtons
- [ ] MaxScaleDenominator
- [ ] MinScaleDenominator
- [ ] ScaleDenominator
- [ ] BulkEditModals
- [ ] ColorMapEditor
- [ ] ChannelField
- [ ] ChannelSelectionField
- [ ] ColorMapEntryField
- [ ] ColorMapTypeField
- [ ] ContrastEnhancementField
- [ ] ExtendedField
- [ ] GrayChannelField
- [ ] RgbChannelField
- [ ] SourceChannelNameField
- [ ] IconSelector
- [ ] IconSelectorWindow
- [ ] RasterChannelEditor
- [ ] SLDRenderer
- [ ] UploadButton

**Comment by jansule** [comment]
Steps to create new examples for components:
1. go to directory of component
2. create new file `<componentname>.example.md` if not exists yet
3. add example code (see existing examples for reference)

**Comment by KaiVolland** [comment]
I think all components are included in the docs now, right? Do we want examples for every component?

**Comment by jansule** [comment]
> I think all components are included in the docs now, right? 

Did you check if they really are? And do they work properly? I'm not really sure about that.

> Do we want examples for every component?

IMHO that would be the goal.

**Comment by jansule** [comment]
The `previewMap` component is missing in our docs
