### ISSUE TITLE
Mapcss parser

### ISSUE THREAD

**Issue by pvgenuchten** [geostyler/geostyler#1175]
### Description:

Idea from foss4g bof
Mapcss is a style format popular in osm community. 

‘’’
Object[attr=val] {
Prop:Val;
}
‘’’

The challenge lays in the fact that mapcss does not follow a layer-paradigm, the css applies to any objecttype in the map, that’s why each rule starts with an object filter.

Not sure how that would match the geostyler approach, which seems to follow the layer paradigm.

**Comment by KaiVolland** [comment]
Hey @pvgenuchten :wave: 

That sounds very cool.

There have been similar concerns with the [geostyler-mapbox-parser](https://github.com/terrestris/geostyler-mapbox-parser) as the mapbox approach is more or less map based. It is hard to translate some layer based style to a map or feature based style and I think a 100% solution will not be possible.

On the other hand the format pretty much looks like a `Rule` so its definitely worth a try.

Whoever came up with this idea should give it a try. As the parsers are completely stand alone it won't hurt anyone if it is not perfect in the end.

We're very happy about the recent participations and conversions about this project. :heart_eyes:

**Comment by chrismayer** [comment]
Thanks @pvgenuchten bringing this issue from the GeoStyler BOF at FOSS4G :+1: 

As already stated on twitter I am really happy that the GeoStyler project gets more attention, even international one :heart_decoration: 

The MapCSS seems to be interesting and since it seems very common in the OSM world it might open up GeoStyler to more users. What came into my mind is if there is any overlapping with the [CSS style format supported by GeoServer](https://docs.geoserver.org/stable/en/user/styling/css/index.html)?

**Comment by allyoucanmap** [comment]
We are currently testing the possible implementation of a GeoCSS parser (the one supported by GeoServer), we are interested to contribute with such parser when it's more stable.
In case we get a working parser what is the best way to contribute to this project?

**Comment by pvgenuchten** [comment]
Pull request is usually the best way. Maybe we should set up a Gitter channel for questions.

**Comment by KaiVolland** [comment]
Hey @allyoucanmap, :tada: 

nice to see that you'd like to contribute. :heart_eyes: 

Currently all the parsers are seperate repositories. So its the easiest way - for you and for us - to keep it this way.

If you'd like to have the parser under the geostyler org at github, I'll create a `geocss-parser` repository with all the stuff you'll need an then you can fork and fill it with your stuff. (Just tell me :nerd_face:)

If you'd like to keep it under your org (which would be totally fine) I'll just add an `community-parsers` section (or somehting like that) to the readme and link yours.

If I may ask for one thing it would be cool if you could orientate your own parser on the existing parsers like [geostyler-sld-parser](https://github.com/geostyler/geostyler-sld-parser) or [geostyler-openlayers-parser](https://github.com/geostyler/geostyler-openlayers-parser).

Mainly its about naming the parser/module etc.

So users can easily find it via npm.

Maybe we should extend the existing documentation on how to develop parsers. You can find it here: 
https://github.com/geostyler/geostyler#developing-geostyler-style-parsers

If you have any further questions on contributing feel free to contact me.

**Comment by allyoucanmap** [comment]
Hi @pvgenuchten @KaiVolland, thanks for the comments!
@KaiVolland we just started with some test by cloning the geostyler-sld-parser and replacing existing file with new .ts files related to GeoCSS parsing, the idea is to follow the structure of existing parser  as you are suggesting (so probably the library name could be `geostyler-geocss-parser`).

> If you'd like to have the parser under the geostyler org at github, I'll create a geocss-parser repository with all the stuff you'll need an then you can fork and fill it with your stuff. (Just tell me 🤓)

If possible we would like to contribute directly to geostyler org repository but I'm wondering if better to wait a basic working parser before open the repository or just open and fork it, let me know what you prefer?

---
I know that probably this is not the right place and I'll move to another section/issue if needed but speaking of contribution we would like also to share some generic wrapper functions we implemented to handle styles with multiple NamedLayer and FeatureTypeStyle to preserve as much as possible the original structure of stylesheets while parsing them.
If you are interested we could contribute to geostyler repository also for this helper functions (even if I don't know where right now), please let me know what do you think.

this are the main functions:

- `styleSheetToGeoStylerStyle(format, styleSheet)` -> reduce the stylesheet to an array of style group
  - `format` {string} currently only 'sld' or 'mbstyle'
  - `styleSheet` {string|object} the actual stylesheet

return `geoStylerStyles` array of style group

```js
// structure of geoStylerStyles
const geoStylerStyles = [
  {
    layerName: 'name',
    group: Style [] // Array of GeoStyler Style
  }
]
```
 
- `geoStylerStyleToStyleSheet(format, geoStylerStyles)`

  - `format` {string} currently only 'sld' or 'mbstyle'
  - `geoStylerStyles` 

return `styleSheet` the stylesheet with separated NamedLayers and FeatureTypeStyle

other functions to this [commits](https://github.com/geosolutions-it/MapStore2/blob/visual-style-editor/web/client/utils/VectorStyleUtils.js#L336-L678) but they are related to the two described above

**Comment by jansule** [comment]
@allyoucanmap we are very happy that you want to contribute to the project!

I just created an empty [repository for geostyler-geocss-parser](https://github.com/geostyler/geostyler-geocss-parser). Feel free to fork it and provide PRs at will.

Don't worry about the development status of the parser. It does not have to be releasable right from the start. It was the same with the other parser as well.

**Comment by jansule** [comment]
@allyoucanmap I created a new issue for the second part of your comment https://github.com/geostyler/geostyler/issues/1175#issuecomment-535993193.

https://github.com/geostyler/geostyler/issues/1201

**Comment by allyoucanmap** [comment]
> I just created an empty repository for geostyler-geocss-parser. Feel free to fork it and provide PRs at will.
> 
> Don't worry about the development status of the parser. It does not have to be releasable right from the start. It was the same with the other parser as well.
> 

@jansule thanks for the repository I'll fork and start to work on it

> @allyoucanmap I created a new issue for the second part of your comment #1175 (comment).
> 
> #1201

I'll comment directly under the issue, thanks again!

**Comment by allyoucanmap** [comment]
@jansule, @KaiVolland,
started to implement some parsing functions to convert geocss to json and a readStyle for Polygon/Fill symbolizer, you can find the fork [here](https://github.com/allyoucanmap/geostyler-geocss-parser).
We were looking for a library to convert geocss to json and back json to geocss but most of css/less/sass converters available don't fulfill requirements for geocss so we are trying an approach with a lexer and opted for this [one](https://github.com/allyoucanmap/geostyler-geocss-parser/blob/master/src/utils/geoCSS2JSON.ts).
That [library](https://github.com/no-context/moo) is under the BSD 3-Clause License so it should be compatible with geostyler license but before to continue on the implementation we would like to have a feedback from you about this, what do you think?

---

We tried also this [library](https://github.com/tuchk4/rockey/tree/master/packages/rockey-css-parse) but unfortunately it didn't cover all the requirements for geocss and it needed wrapping functions to adjust the results anyway.

**Comment by jansule** [comment]
@allyoucanmap I just took a glance at your fork and it looks good so far. Since this is the first css-based parser we are creating, I cannot suggest a good parser. But if [moo](https://github.com/no-context/moo) works good for you, then it is totally fine to use that one.

Feel free to open a WIP PR to the repository at any time. This should simplify code based discussions.

As a source of inspiration for the geocss parser, you can also take a look at the [geoserver/geotools implementation](https://github.com/geotools/geotools/blob/master/modules/unsupported/css/src/main/java/org/geotools/styling/css/CssParser.java) (which I suppose you know already).

**Comment by AllroadsNL** [comment]
In the openingspost  OSM is mentioned. Just what I need.

I use the editor JOSM for editing openstreetmap data.
To see, what is tagged, I made also a style for access visualisation and other tags on the highway important for routing descissions. Visual control compare connecting ways, zoomed in on level we are not editing a legend in text over the icons.
Now I like to use the same style in openlayers, there is the possibility with overpass to download OSM data, when visualised the same it is familiar. Not learning several legends.

With a permalink, the OSM community could discuss situations, pointing out, what is wrong and what could be better.

MAPCSS to ............., could be very helpfull!

**Comment by chrismayer** [comment]
I just added a separate issue for the GeoServer CSS parser to keep things clear since this issue is intended to be a feature request for a MapCSS parser. So any discussion about a GeoServer CSS parser implementation should be done in #1285.

@allyoucanmap I've seen you already did a lot of work in https://github.com/allyoucanmap/geostyler-geocss-parser. Could you please give us an update about the state of work in #1285? Thanks in advance.
