### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by KaiVolland** [geostyler/geostyler#1182]
### Description:
As the subprojects (Parsers, etc.) are growing (also by number) we should think about reopening the Issues for these. This would make it easier to keep the overview.

Also i think Greenkeeper will work even better then.

**Comment by jansule** [comment]
> As the subprojects (Parsers, etc.) are growing (also by number) we should think about reopening the Issues for these. This would make it easier to keep the overview.

I am not sure if this is a good idea. Most of the issues/discussions affect multiple subprojects (e.g. all style parsers) and should thus be discussed at a single point of discussion. 

Issues that only affect a single subproject (e.g. bug in geostyler-sld-parser) would be more useful to have directly linked to the corresponding repository.

However, splitting this up might confuse people on where to open an issue - especially external contributors that are new to the project.

> Also i think Greenkeeper will work even better then.

This is a good point.

**Comment by jansule** [comment]
Any other opinions on that @KaiVolland @chrismayer? Otherwise I will close this issue soon.

**Comment by jansule** [comment]
>  As we have the geostyler org now i even more like the idea of having issues per repo again.

I agree with you on that.

+1 for moving the issues to their respective repos.

**Comment by jansule** [comment]
Activated issues in all repos. Issues will be moved to their repos
