### ISSUE TITLE
React function components and hooks

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler#1187]
### Description:

The "modern" way of writing react applications is using [function components](https://reactjs.org/docs/components-and-props.html) and [hooks](https://reactjs.org/docs/hooks-intro.html), instead of component classes. We should think about whether we want to switch to these concepts or not.

This issue should work as a forum for discussion.

Some pros and cons:

*pro*:
- more reusable code between components
- clearer structure within components (as logically related things will be put together, instead of splitting by lifecycle methods)
- more concise component exports (e.g. currently, we export components with i18n differently from their non-i18n versions)
- better/simpler use of context (used for i18n and compositions)

*con*:
- refactoring all our components
- possibly worse/confusing project structure (due to components sharing logic)

@dnlkoch @KaiVolland @chrismayer @marcjansen @hwbllmnn what do you think?

**Comment by KaiVolland** [comment]
As https://github.com/geostyler/geostyler/pull/1395 shows we'll need to change the way we are testing.

Maybe a switch to https://testing-library.com/docs/react-testing-library/intro/ will be usefull to make writing tests easier.

**Comment by jansule** [comment]
It would be nice, if you could write a few (example) tests using that library, to see if this actually makes things easier for us.

**Comment by jansule** [comment]
That's ok for me. We could also use this issue as an overview of the components that still need to be replaced. You decide.
