### ISSUE TITLE
[geoserver-plugin] Build of plugin fails

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler#1193]
### Description:

The GeoStyler Extension for GeoServer build does not work. Only an empty .zip file can be downloaded from the [geoserver list of community plugins](https://build.geoserver.org/geoserver/master/community-latest/). This should be fixed as soon as possible.

**Comment by hwbllmnn** [comment]
Done with https://github.com/geoserver/geoserver/pull/3780 and https://github.com/geoserver/geoserver/pull/3779

**Comment by jansule** [comment]
PRs were merged and builds succeed.
