### ISSUE TITLE
tslint rule to enforce property descriptions

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler#1195]
### Description:

If you take a look at our API docs you will notice that many component properties do not have a short description. Even though many of the properties are self-explanatory, we should try to provide a short description for every single one.

To enforce this, a tslint rule should be created/added that checks if a property has a description or not.

**Comment by jansule** [comment]
After short research, the only applicable rule I found is [`completed-docs`](https://palantir.github.io/tslint/rules/completed-docs/) with

```json
//tslint
"rule": {
  "completed-docs": [true, "interfaces"]
}
```
The problem here is, it only checks if the interface has JSDocs, not its members.

So

> in this example it's fine:
> 
> ```
> /**
>  * Foo
>  */
> export interface IFoo {
>   foo: string;
> }
> ```
> 
> but I want this as the correct one:
> 
> ```
> export interface IFoo {
>  /**
>   * Foo
>   */
>   foo: string;
> }
> ```



See also https://github.com/palantir/tslint/issues/4627

**Comment by KaiVolland** [comment]
As we do not use `tslint` anymore the es-lint rule you are looking for might be [this one](https://eslint.org/docs/rules/require-jsdoc):
```ts
    "require-jsdoc": ["error", {
        "require": {
            "FunctionDeclaration": true,
            "MethodDefinition": false,
            "ClassDeclaration": false,
            "ArrowFunctionExpression": false,
            "FunctionExpression": false
        }
    }]
```
