### ISSUE TITLE
Handle multiple NamedLayer and FeatureTypeStyle

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler#1201]
From @allyoucanmap in https://github.com/geostyler/geostyler/issues/1175#issuecomment-535993193

> I know that probably this is not the right place and I'll move to another section/issue if needed but speaking of contribution we would like also to share some generic wrapper functions we implemented to handle styles with multiple NamedLayer and FeatureTypeStyle to preserve as much as possible the original structure of stylesheets while parsing them.
> If you are interested we could contribute to geostyler repository also for this helper functions (even if I don't know where right now), please let me know what do you think.
> 
> this are the main functions:
> 
> * `styleSheetToGeoStylerStyle(format, styleSheet)` -> reduce the stylesheet to an array of style group
>   
>   * `format` {string} currently only 'sld' or 'mbstyle'
>   * `styleSheet` {string|object} the actual stylesheet
> 
> return `geoStylerStyles` array of style group
> 
> ```js
> // structure of geoStylerStyles
> const geoStylerStyles = [
>   {
>     layerName: 'name',
>     group: Style [] // Array of GeoStyler Style
>   }
> ]
> ```
> 
> * `geoStylerStyleToStyleSheet(format, geoStylerStyles)`
>   
>   * `format` {string} currently only 'sld' or 'mbstyle'
>   * `geoStylerStyles`
> 
> return `styleSheet` the stylesheet with separated NamedLayers and FeatureTypeStyle
> 
> other functions to this [commits](https://github.com/geosolutions-it/MapStore2/blob/visual-style-editor/web/client/utils/VectorStyleUtils.js#L336-L678) but they are related to the two described above

**Comment by jansule** [comment]
@allyoucanmap thanks for the proposal. We do not handle multiple NamedLayers and FeatureTypeStyles, (yet). Currently, I am not sure where to put that code. 

So I would postpone the decision if/where we should include the code until we come up with a general solution on how to handle multiple NamedLayers and FeatureTypeStyles.

**Comment by allyoucanmap** [comment]
@jansule no problem, thanks for the feedback!

---
I'm adding only a note about the reason behind multiple FeatureTypeStyles, so there is more context about this proposal.
We needed this kind of wrapper to render chasing of lines.
This is our tests:

Following styles return overlapped lines
- Multiple Rules
- Multiple LineSymbolizers
```xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<StyledLayerDescriptor version="1.0.0"
                         xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd"
                         xmlns="http://www.opengis.net/sld"
                         xmlns:ogc="http://www.opengis.net/ogc"
                         xmlns:xlink="http://www.w3.org/1999/xlink"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NamedLayer>
    <Name>Default Line</Name>
    <UserStyle>
      <Title>Default Line</Title>
      <FeatureTypeStyle>
        <Rule>
          <Name>Rule 1</Name>
          <LineSymbolizer>
            <Stroke>
              <CssParameter name="stroke">#ff33aa</CssParameter>
              <CssParameter name="stroke-width">10</CssParameter>
            </Stroke>
          </LineSymbolizer>
          <LineSymbolizer>
            <Stroke>
              <CssParameter name="stroke">#33ffaa</CssParameter>
              <CssParameter name="stroke-width">4</CssParameter>
            </Stroke>
          </LineSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>
```
```xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<StyledLayerDescriptor version="1.0.0"
                       xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd"
                       xmlns="http://www.opengis.net/sld"
                       xmlns:ogc="http://www.opengis.net/ogc"
                       xmlns:xlink="http://www.w3.org/1999/xlink"
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NamedLayer>
    <Name>Default Line</Name>
    <UserStyle>
      <Title>Default Line</Title>
      <FeatureTypeStyle>
        <Rule>
          <Name>Rule 1</Name>
          <LineSymbolizer>
            <Stroke>
              <CssParameter name="stroke">#ff33aa</CssParameter>
              <CssParameter name="stroke-width">10</CssParameter>
            </Stroke>
          </LineSymbolizer>
        </Rule>
        <Rule>
          <Name>Rule 2</Name>
          <LineSymbolizer>
            <Stroke>
              <CssParameter name="stroke">#33ffaa</CssParameter>
              <CssParameter name="stroke-width">4</CssParameter>
            </Stroke>
          </LineSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>

```
Preview for both styles above, there are overlapping to the join of different line geometries:

![image](https://user-images.githubusercontent.com/19175505/65896659-e7d73980-e3ad-11e9-93ae-6c726c9fe676.png)

While with Multiple FeatureTypeStyles this is the result
```xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<StyledLayerDescriptor version="1.0.0"
                       xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd"
                       xmlns="http://www.opengis.net/sld"
                       xmlns:ogc="http://www.opengis.net/ogc"
                       xmlns:xlink="http://www.w3.org/1999/xlink"
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NamedLayer>
    <Name>Default Line</Name>
    <UserStyle>
      <Title>Default Line</Title>
      <FeatureTypeStyle>
        <Rule>
          <Name>Rule 1</Name>
          <LineSymbolizer>
            <Stroke>
              <CssParameter name="stroke">#ff33aa</CssParameter>
              <CssParameter name="stroke-width">10</CssParameter>
            </Stroke>
          </LineSymbolizer>
        </Rule>
      </FeatureTypeStyle>
      <FeatureTypeStyle>
        <Rule>
          <Name>Rule 1</Name>
          <LineSymbolizer>
            <Stroke>
              <CssParameter name="stroke">#33ffaa</CssParameter>
              <CssParameter name="stroke-width">4</CssParameter>
            </Stroke>
          </LineSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>

```

Preview, the lines continue to the join between different geometries:
![image](https://user-images.githubusercontent.com/19175505/65896777-34bb1000-e3ae-11e9-88f0-11182aa0aac5.png)

We tried to render this style parsed with geostyler with OpenLayers, MapBoxGL and GeoServer and to get the second preview we created the proposed functions.
