### ISSUE TITLE
Label on Polygon not visible (Openlayers-Renderer)

### ISSUE THREAD

**Issue by fschmidt56** [geostyler/geostyler#1207]
# Bug

**Describe the bug**
When styling polygon with fill-symbolizer and text-symbolizer, the text will not be displayed in the symbolizer-preview (OpenLayers)

**To Reproduce**
1. load default wfs via load data
1. choose Openlayers-renderer
2. paste following json into code editor
3. preview does not show label
```json
{
  "name": "SLD Cook Book: Polygon with default label",
  "rules": [
    {
      "name": "Polygon with default label",
      "symbolizers": [
        {
          "kind": "Fill",
          "color": "#0E1058",
          "opacity": null
        },
        {
          "kind": "Text",
          "label": "Your Label",
          "size": 12
        }
      ]
    }
  ]
}
```
**Expected behavior**
preview should show label and fill-style

**Screenshots**

![grafik](https://user-images.githubusercontent.com/56070927/66375149-f8d70a80-e9ac-11e9-909b-d935b7a8ead1.png)

**Desktop (please complete the following information):**
 - Browser

**Comment by KaiVolland** [comment]
Seems to be an issue for every `TextSymbolizer`.

**Comment by jansule** [comment]
> Seems to be an issue for every `TextSymbolizer`.

Not with OpenLayers Renderer. There, labels in combination with points, lines and icons seems to work fine

**Comment by KaiVolland** [comment]
Regular overlapping text will not be displayed on a polygon, so this is why there is no text to see in this example. Changing the text to "Y" shows the difference.
Nevertheless the `allowOverlap` was never parsed correctly. But with geostyler/geostyler-openlayers-parser#412 it is. So this can be closed.
