### ISSUE TITLE
geostyler-legend: missing dependency 'd3-selection'

### ISSUE THREAD

**Issue by jahow** [geostyler/geostyler#1209]
# Bug

**Describe the bug**
When doing `npm install geostyler-legend` and then using the example snippet, the following error is thrown by webpack at compile time:
```
ERROR in <project-path>/node_modules/geostyler-legend/dist/LegendRenderer/LegendRenderer.js
Module not found: Error: Can't resolve 'd3-selection' in <project-path>/node_modules/geostyler-legend/dist/LegendRenderer'
```

Doing `npm install d3-selection` solves the issue.

**To Reproduce**
1. install package
```bash
npm install --save geostyler-legend
```

2. use the following import:
```js
import LegendRenderer from 'geostyler-legend/dist/LegendRenderer/LegendRenderer'
```

3. use the renderer:
```js
    const renderer = new LegendRenderer({
      maxColumnWidth: 300,
      maxColumnHeight: 300,
      overflow: 'auto',
      styles: [style],
      size: [600, 300],
    })
    renderer.render(element)
```

**Expected behavior**
No need to install dependencies manually.

**Additional context**
This happened on an angular 7 project.

**Comment by jansule** [comment]
@jahow did you also run `npm install d3@^5`?

d3 is a peerDependency of geostyler-legend and has to be installed manually (see [here](https://github.com/geostyler/geostyler-legend/blob/a21d8cc60bd72c002202c0cca1e9ab7f7ef77942/package.json#L28-L36)). d3-selection is a direct dependency of d3 so it should then be installed automatically as well.

Please let me know, if that solves your issue.

**Comment by jahow** [comment]
Hi,

I have used a work around so this is not blocking my project any more, but thanks for the insight. Why not declare `d3` as a regular dependency?

**Comment by jansule** [comment]
> so this is not blocking my project any more

Glad to hear that!

> Why not declare `d3` as a regular dependency?

One of the reasons is that when using dependencies that are probably also being used by the parent application, we try to avoid having duplicate versions of that dependency, in order to keep the build size small(er).
