### ISSUE TITLE
[OpenLayers Parser] outlineDasharray property not recognized

### ISSUE THREAD

**Issue by jahow** [geostyler/geostyler#1222]
# Bug

**Describe the bug**
The `outlineDasharray` property of fill symbolizers is not recognized by the OpenLayers parser.

**To Reproduce**
1. Go to https://geostyler.github.io/geostyler-demo/
2. Use following style:
```json
{
  "name": "Demo Style",
  "rules": [
    {
      "name": "Rule 1",
      "symbolizers": [
        {
          "kind": "Fill",
          "color": "#eeeeee",
          "outlineWidth": 8,
          "outlineColor": "#ff0000",
          "outlineDasharray": [
            4,
            4
          ]
        }
      ]
    }
  ]
}
```
3. Set preview to OL and get result:
![image](https://user-images.githubusercontent.com/10629150/71168374-d720bc00-2256-11ea-897c-3f669c57320d.png)

The SLD preview is the following:
![image](https://user-images.githubusercontent.com/10629150/71168366-d0924480-2256-11ea-9a63-a6a46961e72c.png)

**Expected behavior**
SLD and OL preview should be identical.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox 71

---

Let me know if we can make a PR to fix this on the parser. Thanks!

**Comment by KaiVolland** [comment]
Hey Olivier. Thanks for the report. PRs are always welcome.
