### ISSUE TITLE
Symbolizer too large (using browser-bundle in a non-react web application)

### ISSUE THREAD

**Issue by chrismayer** [geostyler/geostyler#1238]
# Bug
Not sure if this is a real bug in GeoStyler, but I try to explain for the case anyone has an idea what is going wrong and to give other devs a platform if they discover the same behaviour.

**Describe the bug**
I am using GeoStyler as browser-bundle in a non-react web application. The GeoStyler UI (compact mode) is rendered within a div in the browser DOM. The first time  the GeoStyler gets rendered (after application startup) the symbolizer preview in the rule table is rendered too large, so its boundaries are moved outside the visible area. In case of having a "Fill Symbolizer" with a transparent fill it looks like the symbolizer preview is not working at all. What really happens is that the outline of the symbolizer is shifted to the non-visible area (see section `Screenshots`).

**To Reproduce**
I could not reproduce the behaviour in a public GeoStyler instance (e.g. geostyler-demo-app). Therefore I am not sure if the setup (using browser-bundle in non-react webapp) is the reason for this.

**Expected behaviour**
The symbolizer is appears in the correct size the first time the GeoStyler is rendered to the DOM. 

**Screenshots**

Buggy:
![grafik](https://user-images.githubusercontent.com/1185547/73342391-c1071200-427e-11ea-9bd1-4e2b3693ffdf.png)

Correct:
![grafik](https://user-images.githubusercontent.com/1185547/73346996-2828c480-4287-11ea-9f09-a224fb39ac65.png)

**Desktop (please complete the following information):**
 - OS: Linux / Ubuntu 18.04
 - Browser: Chrome / Chromium (79) and Firefox (72)

**Additional context**
The style is loaded as SLD and transformed to GeoStyler style before it is applied.

```xml
...
  <PolygonSymbolizer>
    <Stroke>
      <CssParameter name="stroke">#0000ee</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
    </Stroke>
  </PolygonSymbolizer>
...
```

**Comment by KaiVolland** [comment]
Hmm. We don't have this issue in our applications which use the browser-bundle.

**Comment by KaiVolland** [comment]
@chrismayer is this issue still valid. If not please close it.
