### ISSUE TITLE
Mapnik parser

### ISSUE THREAD

**Issue by rowanwins** [geostyler/geostyler#1281]
# Parser Request

**Describe the parser you would like to request**
Would be awesome to support a Mapnik style parser.

**Additional context**
Here's a sample mapnik style. 
````
    <Style name="basic">
        <Rule>
            <PolygonSymbolizer fill="#eeeeee" clip="true" />
            <LineSymbolizer stroke="#000000" stroke-width="1" clip="true" />
        </Rule>
    </Style>
````
And here is some [doco](https://github.com/mapnik/mapnik/wiki/SymbologySupport)

**Comment by KaiVolland** [comment]
Looks definetly doable. As we never worked with Mapnik styles and i know nothing about an upcoming project i think we wont be able to implement this parser.

But maybe there are some cool guys out there (im talking about you :wink:) who could do this.

**Comment by rowanwins** [comment]
Haha yep I'm happy to contribute @KaiVolland - not sure I'm cool though :)

I might start it in a personal repo and if and when I get it done I'm happy to change the ownership. I'll probably base it off the SLD parser.

**Comment by chrismayer** [comment]
Happy to hear that you are willing to contribute :+1: Thanks in advance. Strategy starting in a personal repo sounds good. Give us a ping if you need some feedback or reviews.
