### ISSUE TITLE
GeoServer CSS Parser

### ISSUE THREAD

**Issue by chrismayer** [geostyler/geostyler#1285]
# Parser Request

**Describe the parser you would like to request**
A parser for the [CSS based styling format supported by GeoServer](https://docs.geoserver.org/stable/en/user/styling/css/index.html) would be a very useful addition for the GeoStyler ecosystem. The need for it evolved somehow in the issue #1175 and this issue tries to split things up to have a separate issue for a GeoServer CSS Parser.

**Additional context**
As stated above there was a lot of discussion about implementing a  GeoServer CSS Parser in #1175. Even some work has already been done by @allyoucanmap in https://github.com/allyoucanmap/geostyler-geocss-parser.

**Comment by allyoucanmap** [comment]
> @allyoucanmap I've seen you already did a lot of work in https://github.com/allyoucanmap/geostyler-geocss-parser. Could you please give us an update about the state of work in #1285? Thanks in advance.

Hi @chrismayer, here some updates on the GeoCSS parser:
- I needed to refactor my previous work on the tokenizer to read and write the geocss and to do so I decided to focus only on one of the directives provided by GeoCSS: the 'Flat' mode. So I created a separate repository where I tried to implement it [flat-geo-css](https://github.com/allyoucanmap/flat-geo-css). This version of Flat mode is a bit limited compared with the GeoTools one and it has still some issue but it seems to work on styles with low complexity.
- Recently I tried to import the library described above on the fork 
https://github.com/allyoucanmap/geostyler-geocss-parser adding some functions for the readStyle parts and tests.

I'll try to update the missing parts on the geostyler-geocss-parser but I'm not sure when I could work on it due the fact I'm working on this on my spare time.

**Comment by chrismayer** [comment]
Hi @allyoucanmap,

thanks for the update. Sounds promising. Let us know if we can provide any help. In case you are ready (no pressure on that) we might consider moving the geocss-parser to the official GeoStyler organisation (only if you agree of course). So others can find it more easily and provide code as well. But first steps first. Just write here if there are any news.

Thank you!

**Comment by allyoucanmap** [comment]
Hi @chrismayer,

I was working on a fork of https://github.com/geostyler/geostyler-geocss-parser so I just did a [PR](https://github.com/geostyler/geostyler-geocss-parser) with the current state of the parser.
