### ISSUE TITLE
Is `canvas` not a devDependency now?

### ISSUE THREAD

**Issue by initialdmg** [geostyler/geostyler#1289]
https://github.com/geostyler/geostyler/blob/a8920a84feffec2eba50c99ae8c1d88d22d8ee34/package.json#L62

Before commit [Replaces canvas-prebuilt (deprecated) with canvas](https://github.com/geostyler/geostyler/commit/58d9d6c24d841bc0f66c9f71c00bb6ea3db5be7e), `canvas-prebuilt` is a dev dependency, but after that replacement `canvas` changed to a dependency, but i cannot find any usage in the code. Is that a expected change?

**Comment by marcjansen** [comment]
Ping @KaiVolland

**Comment by KaiVolland** [comment]
If i remember right `canvas` and `canvas-prebuilt` are required to run tests with openlayers stuff. So i guess you're right. Nice catch.

If you'd like you could just open a PR with canvas in `devDependencies`. CI will no better if you're right. :)

**Comment by initialdmg** [comment]
Resolved by #1291 .
