### ISSUE TITLE
Version mismatch?

### ISSUE THREAD

**Issue by chrismayer** [geostyler/geostyler#1300]
# Question

A couple of days ago a release [v4.6.0](https://github.com/geostyler/geostyler/releases/tag/v4.6.0) has been created. The version tag in the `package.json` still [states 4.5.0](https://github.com/geostyler/geostyler/blob/master/package.json#L3). Do I oversee something or is there a missing update of the `package.json`? If this is the case we should make this a bug report.

I have some problems running the local development setup of `geostyler-demo` which pointed me to that and might be related.

**Comment by KaiVolland** [comment]
Forgot to push to upstream. Sorry. Should be fixed now.
