### ISSUE TITLE
OGC Symbology Conceptual Model (SymCore)

### ISSUE THREAD

**Issue by b4l** [geostyler/geostyler#1301]
# Question

Recently the OGC Symbology Conceptual Model (SymCore) standard has been approved. https://gisuser.com/2020/10/ogc-membership-approves-new-standard-symbology-conceptual-model-core-part/

Are there any plans to integrate this into the geostyler-style?

Any thoughts, ideas, wishes, remarks ...

**Comment by jansule** [comment]
Thanks for the info. We did not yet think about implementing it, but we can use this issue to discuss this (ping @KaiVolland @chrismayer @dnlkoch @marcjansen ).

Do I understand correctly, that the SymCore specification allows custom styling properties on certain extension points that an implementing instance will understand how to interpret, but other instances might not?

E.g. a Rule could look like this (with `weight` being a parameter supported by a specific implementation):

```xml
<Rule>
  <name>myRule</name>
  <title>My Rule</title>
  <abstract>This is a Rule</abstract>
  <symbolizer>...</symbolizer>

  <!-- Custom parameter-->
  <weight>2</weight>

</Rule>
```

Or am I on the wrong track?
