### ISSUE TITLE
How do I dynamically set the SLD style based on properties

### ISSUE THREAD

**Issue by wmengs** [geostyler/geostyler#1305]
# Question
16/5000 
How do I dynamically set the color of a surface based on data properties？

For example, I have a piece of data with a 'color' attribute. The attribute value is used to set the color of the data. The SLD style is:
   <PolygonSymbolizer>
            <Fill>
              <CssParameter name="fill">
              	<ogc:PropertyName>color</ogc:PropertyName>
              </CssParameter>
              <CssParameter  name="fill-opacity">1</CssParameter>
               
            </Fill>
            <Stroke>
              <CssParameter  name="stroke">
                <ogc:PropertyName>color</ogc:PropertyName></CssParameter>
              <CssParameter  name="stroke-width">1</CssParameter>
            </Stroke>
          </PolygonSymbolizer>

Why doesn't the SldStyleParser recognize the SLD style format?

**Comment by jansule** [comment]
@wmengs currently we do not support setting the stroke parameter dynamically within a single rule.

We do have a classification feature in the geostyler-ui that creates distinct rules based on data properties, but that does not support setting the color value directly from the data, but rather applies an explicitly defined color palette.

Supporting dynamic rules would be a nice feature to have. Would you like to create a PR for that?

**Comment by KaiVolland** [comment]
This is related to https://github.com/geostyler/geostyler-sld-parser/issues/697
