### ISSUE TITLE
GeoServer Plugin

### ISSUE THREAD

**Issue by KaiVolland** [geostyler/geostyler#1320]
- Figure out what TODOs we have to make the plugin usable
- Enhance the visibility of the plugin itself

**Comment by weskamm** [comment]
My current findings.
Tested with latest stable 2.18.2:

Issues:
  * open geostyler tab on a rastersymbolizer SLD
    * geostyler does not appear
    * layerpreview does not appear
    * fontsize seems to be changed on the whole page -> bad css?!
    * console throws warns and erros:
      * Warn: @babel/polyfill is loaded more than once
      * Error: Wicket.Ajax:  Cannot bind a listener for event "click" on element "idfa" because the element is not in the DOM
      * WFS Data Parser does a describefeature call for a raster style -> leads to errors
https://github.com/geoserver/geoserver/blob/051d7a91c3dae51e18b71a344f3867687c722b2b/src/community/geostyler/src/main/resources/org/geoserver/wms/web/data/geostyler-init.ftl#L19
      * Error: Uncaught (in promise) Could not parse XML document: TypeError: Cannot read property 'forEach' of undefined

  * open geostyler tab on a polygonsymbolizer SLD
    * geostyler appears
    * layerpreview does not appear
    * fontsize seems to be changed on the whole page -> bad css?!
    * console throws warns and erros:
      * Warn: @babel/polyfill is loaded more than once
    * Some Workflow logs to console "onchange" and the SLD body
      * see https://github.com/geoserver/geoserver/blob/051d7a91c3dae51e18b71a344f3867687c722b2b/src/community/geostyler/src/main/resources/org/geoserver/wms/web/data/geostyler-init.ftl#L58
    * CSS seems to be bad when entering fullscreen mode, not sure if this related to the plugin or a generic issue (can be also seen on default style tab)

    * Code needs overall cleanup, linting and update

Ideas:
  * Make SLD Editor collapsible? -> Size (height) can become an issue with geostyler and SLD editor shown at the same time

**Comment by weskamm** [comment]
discussion can be found here: https://github.com/geostyler/geostyler/discussions/1324

**Comment by KaiVolland** [comment]
Moved to discussions.
