### ISSUE TITLE
PreviewMap : Zoom interaction

### ISSUE THREAD

**Issue by sonyz** [geostyler/geostyler#1325]
# Question

Hi,
I'm a new user of your great tool and sorry if the question has been already asked. 

I'm just wondering why we cannot zoom on the Preview Map component ? It seems to be disabled.
I think it would be interesting for the users to see when the rules is applied or not depending zoom level (defined by the min. scale and max. scale) and see the rules sequence.
Maybe does it exist a technical limitation ?

Thanks!

**Comment by jansule** [comment]
Happy to hear that you like our tool!

You can configure interactions on the `PreviewMap` component via its `interactions` property (see [here](https://github.com/geostyler/geostyler/blob/508b11e37f595e598bf4cd53a601ae67883fd5bd/src/Component/PreviewMap/PreviewMap.tsx#L70)).

This property expects a list of [OpenLayers interactions](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Interaction-Interaction.html).

I just noticed that the `PreviewMap` component is missing in our docs. We will add it soon.

**Comment by sonyz** [comment]
Thank you for your reply ! I will try to add the interactions like zoom. Maybe it will be useful to see the zoom interaction in the demo app.

**Comment by jansule** [comment]
> Maybe it will be useful to see the zoom interaction in the demo app.

Absolutely agree with you on that. 

It would be awesome, if you can provide a PR for that to [geostyler-demo](https://github.com/geostyler/geostyler-demo).
