### ISSUE TITLE
Default value for InputNumber components

### ISSUE THREAD

**Issue by initialdmg** [geostyler/geostyler#1346]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Add defaultValue prop to InputNumbers. This may cause parse issue, i dont know..., but i think that might make ui clearer with a specific number in  the component 😄 

**Describe the solution you'd like**
Set a specific defaultValue prop on related components

**Describe alternatives you've considered**

**Additional context**

**Comment by KaiVolland** [comment]
Hey @initialdmg this is now possible with the `DefaultValueContext` introduced in version 5.1.0
