### ISSUE TITLE
Still some problems with opacity handling in Symbolizer Editor

### ISSUE THREAD

**Issue by verendi** [geostyler/geostyler#1359]
# Bug

**Describe the bug**

1. For polygons, Fill-Opacity value can be set and is applied and saved to the style, but it does not show up when editing this rule again (so the user cannot see that this value is already set).
2. For points, the Stroke-Opacity works fine, but the Fill-Opacity is not working (is not applied to the style).

**To Reproduce**
1. For the polygons issue, open the Symbolizer Editor in rule of a polygon style and set a Fill-Opacity value. Close the Symbolizer Editor and open it again.
2. For the points issue, open the Symbolizer Editor in rule of a point style and try to set the Fill-Opacity value.

**Expected behavior**

1. For the polygons issue, the saved Fill-Opacity value should be visible in the Symbolizer Editor.
2. For the points issue, the Fill-Opacity should be applied to the style.

**Screenshots**

1. Polygon issue
![geostyler2](https://user-images.githubusercontent.com/1021699/109810519-e99fcf00-7c29-11eb-8f44-d80529c168f6.png)

1. Point issue
![geostyler1](https://user-images.githubusercontent.com/1021699/109810603-063c0700-7c2a-11eb-8f2c-d6cbf8396c86.png)

**Desktop:**
 - OS: Linux Mint 19.1
 - Browser: Chromium Version 87.0.4280.66

**Additional context**
* Detected in version 5.0.1
* Probably related to https://github.com/geostyler/geostyler/pull/1347

**Comment by weskamm** [comment]
I may have a fix for this, at least if SLD is involved. Will try to cross reference here

**Comment by KaiVolland** [comment]
We need to be precise on `opacity`, `fill-opacity` and `stroke-opacity`. `opacity` is missing in the above symbolizer-editors which might be a problem.

**Comment by weskamm** [comment]
> I may have a fix for this, at least if SLD is involved. Will try to cross reference here

only related to SLD 1.1, see https://github.com/geostyler/geostyler-sld-parser/pull/289/files#diff-03b9f5ee99035e0bf89d2385871c79bce270f81666e5bf0cc8e4a13ccbfe3f15L400-R451

**Comment by KaiVolland** [comment]
Should be fixed with https://github.com/geostyler/geostyler/pull/1374. Pleas try again with version 5.1.0.

**Comment by jansule** [comment]
Actually fixed in [v6.0.0](https://github.com/geostyler/geostyler/releases/tag/v6.0.0)
