### ISSUE TITLE
Translation is not used correctly

### ISSUE THREAD

**Issue by mholthausen** [geostyler/geostyler#1417]
# Bug

**Describe the bug**
Changing the language for GeoStyler does not work correctly. This is traceable in the demo as well as in projects where the GeoStyler is included (both in version 6.0.0 and in version 5.0.2).
On the demo page, the language of the elements changes except for those provided by GeoStyler itself (e.g. Symbolizer Editor).

**To Reproduce**
a) Change the language on the demo page and open the editor of any rule. The labels will still be displayed in the default language and not in the selected one.

b) set the config provider:

```javascript
import {
  CompositionContext,
  ConfigProvider,
  Style,
  locale as GsLocale
} from 'geostyler';

import { Style as GsStyle } from 'geostyler-style';

import OlParser from 'geostyler-openlayers-parser';

// …

<ConfigProvider locale={GsLocale.de_DE}>
  <CompositionContext.Provider value={composition}>
    <Style
      enableClassification={false}
      style={style}
      compact={true}
      onStyleChange={(newStyle: GsStyle) => {
        setStyle(newStyle);
      }}
    />
  </CompositionContext.Provider>
</ConfigProvider>

```
**Expected behavior**
That the labels of the GeoStyler are displayed in the selected or in the ConfigProvider specified language.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1
 - Browser: Chrome
 - Version: 89.0.4389.114

**Additional context**
Possibly this is due to the update to antd version 4?

**Comment by marcjansen** [comment]
https://geostyler.github.io/geostyler-demo/ changes the language for some UI components, is this still a valid issue?

**Comment by jansule** [comment]
@marcjansen yes it is. Currently, only texts coming from geostyler-demo are changed. Texts within the geostyler lib are not.
