### ISSUE TITLE
Default Values in Parsers

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler#1444]
# Feature Request

**Is your feature request related to a problem? Please describe.**

When using our parsers for converting one external format to another external format, the input and output styles might differ. This is due to the external formats having different default values.

**Describe the solution you'd like**

It would be nice, if we provide default values, when parsing external styles to geostyler-style. Through this, we can achieve a higher similarity between input and output styles.

We should discuss, to which extend default values should be used. Maybe a good starting point is providing the unit for numeric values, where no unit is set explicitly.

**Describe alternatives you've considered**

...

**Additional context**

Example: We want to convert a mapfile style to SLD. The default unit for numeric values in mapfile styles differs from the default unit in SLDs. This leads to visual differences, when rendering a layer with the input and the output style, respectively. When supporting default values, these differences should be minimized.

This issue is related to https://github.com/geostyler/geostyler-style/issues/188

**Comment by dnlkoch** [comment]
As discussed in the monthly (2022/05/03) default values should be set in the UI (and/or any optional postprocessing).

**Comment by KaiVolland** [comment]
Default values can be set via Context since https://github.com/geostyler/geostyler/pull/1374
