### ISSUE TITLE
geostyler-style/dist/style.d.ts:135:32 - error TS1110: Type expected.

### ISSUE THREAD

**Issue by oussamaam** [geostyler/geostyler#1470]
# geostyler-style/dist/style.d.ts:135:32 - error TS1110: Type expected.

I encountered this error when I was trying to install  **geostyler-sld-parser** using **Angular 10**.
No errors showing up in Visual Studio Code in the **style.d.ts** file, but compilation fails with the error: 
**ERROR in node_modules/geostyler-style/dist/style.d.ts:135:32 - error TS1110: Type expected.
135 export declare type FontSpec = `ttf://${string}#0x${string}`;**

I have typescript v4.0.5 installed. 

Angular CLI: 10.2.0
Node: 14.17.0
OS: win32 x64

Angular: 10.2.3

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@angular/cli                    10.2.0
@schematics/angular             10.2.0
@schematics/update              0.1002.0
rxjs                            6.6.3
typescript                      4.0.5

![image](https://user-images.githubusercontent.com/29263440/125306028-22198d00-e32f-11eb-9421-5f8b253d7724.png)

**Comment by jansule** [comment]
Unfortunately, I cannot reproduce your error.

Could you try upgrading your `typescript` version? geostyler-sld-parser expects `typescript=^4.2.4`.

Also, it might help to look at https://github.com/geostyler/geostyler-demo/ and compare your webpack (or other) build configuration. When installing via `npm`, you do not have to compile `geostyler-sld-parser`.

**Comment by oussamaam** [comment]
@jansule , Thank you for the reply. I tried to upgrade the typescript version  but **Angular 10 Compiler** 
requires  **TypeScript >=3.9.2 and <4.1.0** .
So the problem still exists , is there a version of geostyler-sld-parser  expects **typescript<4.1.0** ?

**Comment by jansule** [comment]
`geostyler-sld-parser@2.2.2` runs on `typescript@3.9.7`, you can try that.

Before that, better try setting `"skipLibCheck": true` in your `tsconfig.json`. See also https://www.typescriptlang.org/tsconfig#skipLibCheck.

**Comment by jansule** [comment]
Seems like this issue was solved. If not, feel free to reopen this issue.
