### ISSUE TITLE
Do not silently remove unsupported features from e.g. SLD

### ISSUE THREAD

**Issue by weskamm** [geostyler/geostyler#1485]
# Feature Request

The demo / parsers should not remove unsupported things from the source one enters as input.
Currently, you can e.g. paste any SLD into the editor of the demo. After the first parsing / transformation is done, not supported features will get silently removed.
Instead it would be nice if the code (unsupported features) would be commented or an message would appear indicating missing support.

**Comment by KaiVolland** [comment]
Compare https://github.com/geostyler/geostyler/issues/286

**Comment by marcjansen** [comment]
This can be closed, I guess. We now give feedback, when we happen to parse sth. unsupported, correct?
