### ISSUE TITLE
GeoStyler not working with Node 16

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler#1524]
# Bug

**Describe the bug**

Currently, it is not possible to install GeoStyler with Node 16.

**To Reproduce**

1. Create an empty directory and `cd` into that directory
2. Run `npm i geostyler`
3. See how it fails with following error message

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@">=16.0.0" from @ant-design/icons@4.7.0
npm ERR!   node_modules/@ant-design/icons
npm ERR!     peer @ant-design/icons@"4.x" from geostyler@7.2.1
npm ERR!     node_modules/geostyler
npm ERR!       geostyler@"*" from the root project
npm ERR!     @ant-design/icons@"^4.6.3" from antd@4.16.13
npm ERR!     node_modules/antd
npm ERR!       peer antd@"4.x" from geostyler@7.2.1
npm ERR!       node_modules/geostyler
npm ERR!         geostyler@"*" from the root project
npm ERR!   peer react@"17.0.2" from react-dom@17.0.2
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@">=16.0.0" from @ant-design/icons@4.7.0
npm ERR!     node_modules/@ant-design/icons
npm ERR!       peer @ant-design/icons@"4.x" from geostyler@7.2.1
npm ERR!       node_modules/geostyler
npm ERR!         geostyler@"*" from the root project
npm ERR!       1 more (antd)
npm ERR!     peer react-dom@">=16.9.0" from antd@4.16.13
npm ERR!     node_modules/antd
npm ERR!       peer antd@"4.x" from geostyler@7.2.1
npm ERR!       node_modules/geostyler
npm ERR!         geostyler@"*" from the root project
npm ERR!   1 more (antd)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.x" from geostyler@7.2.1
npm ERR! node_modules/geostyler
npm ERR!   geostyler@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```

**Expected behavior**

It should be able to install GeoStyler in Node 16.

**Screenshots**

None

**Desktop (please complete the following information):**

Not important in this case.

**Smartphone (please complete the following information):**

Not important in this case.

**Additional context**

See also https://github.com/geostyler/geostyler-style/issues/302

**Comment by KaiVolland** [comment]
I don't think this is a bug in geostyler and i think it's not even related to node 16 but to npm > 7.
As of version 7 npm automatically installs peerDependencies.
GeoStyler has `peerDependencies` to `antd`, `react` and  `react-dom`.
`antd` itself has configured `react` and  `react-dom` as a `peerDependency` to but with a wider range (`"react": ">=16.9.0"`).
This leads to conflicts in what to install when just typing `npm i geostyler`.

So what you want is to install `geostyler` and at the same time install `react` and `react-dom`:

```
npm i react@16 react-dom@16 geostyler
```

On the other hand we should check if geostyler is already compatible with react 17 and widen our peerDependency configuration accordingly.

**Comment by KaiVolland** [comment]
Should be solved with https://github.com/geostyler/geostyler/pull/1594.
