### ISSUE TITLE
[antd: Menu] `children` will be removed in next major version. Please use `items` instead

### ISSUE THREAD

**Issue by Navid61** [geostyler/geostyler#1645]
# Bug

**Describe the bug**
I did try to launch "https://geostyler.github.io/geostyler-beginner-workshop/" in my Laptop, when I run final step code I got warning message in my browser:

index.js:1437 
        
       Warning: [antd: Menu] `children` will be removed in next major version. Please use `items` instead.
 
        
       Warning: SubMenu should not leave undefined `key`.

        
       Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Wrap

        
         Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Wrap

Learn more about this warning here: https://reactjs.org/link/legacy-context
    at Wrap (http://localhost:3000/static/js/0.chunk.js:124041:40)

        
       Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Wrap

I'm going to know How can I solve these error messages? I did upgrade "antd" library to latest version, but they didn't appeared or didn't solved.

**To Reproduce**
1.I did launch final step in GeoStyler Beginner Workshop

**Expected behavior**
run without those error messages I mentioned above 

**Screenshots**
![GeoStyler_bug](https://user-images.githubusercontent.com/4729469/167702814-aa6d33a4-1129-4999-b11d-7a018a135ba6.png)

**Desktop (please complete the following information):**
 - OS: LMDE v5 X64
 - Browser : Microsoft Edge 
 - Version 101.0.1210.39 (Official build) (64-bit)

**Comment by KaiVolland** [comment]
Thx for the report. We will have a look at this.

**Comment by KaiVolland** [comment]
The warning regarding the antd menu is related to the newest version of antd (4.20.0): https://ant.design/components/menu/#Usage-upgrade-after-4.20.0
If you like it would be nice if you can have a look at this and provide a MR.

**Comment by Navid61** [comment]
Thank you so much.
