### ISSUE TITLE
Adapt build scripts to both linux and windows based dev environment

### ISSUE THREAD

**Issue by slafayIGN** [geostyler/geostyler#1726]
There are issues in `transform-less.js` and  `webpack.browser.config.js` that cause errors on build in windows environment.

The directory separator seems involved and it may be solved with the use of the `path` module when working with directories instead of string concatenation.

I will make a pull request.

----

Tasks:

- [x] npm run build-dist
- [x] npm run build-browser
- [x] npm run build-styleguide
- [ ] npm run test

**Comment by jansule** [comment]
Is this issue solved?

**Comment by slafayIGN** [comment]
Not completely, there is still an issue with the `build-styleguide` command which seems environment related.

```
Module parse failed: Unexpected token (63:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| // i18n
> export interface CodeEditorLocale {
|   downloadButtonLabel: string;
|   formatSelectLabel: string;
```

I didn't figure out what could be the cause in `styleguide.config.js`, but didn't spent much time on it yet.

**Comment by slafayIGN** [comment]
```npm run test``` doesn't find any test in the code.

I expected it to be a slash-backslash issue on windows but it seems it's not.

I managed to make things work with a single change in [jest.config.js](https://github.com/geostyler/geostyler/blob/0b7f02f32691408106de6f436a2eab628288be37/jest.config.js#L46-L49) :

```
   testMatch: [
     "<rootDir>/src/**/__tests__/**/*.(j|t)s?(x)",
-    "<rootDir>/src/**/?(*.)(spec|test).(j|t)s?(x)"
+    "<rootDir>/src/**/*(*.)(spec|test).(j|t)s?(x)"
   ],
```

It finds 90 test suites and 381 tests.

I'm not sure I understand why `?(*.)` doesn't work and why `*(*.)` is ok. Both are valid patterns : https://github.com/micromatch/micromatch#extglobs

Would this change be ok on other environments ?

**Comment by jansule** [comment]
> Would this change be ok on other environments ?

Yes, this would be ok for me
