### ISSUE TITLE
the size of iconSymbolizer

### ISSUE THREAD

**Issue by yang6626** [geostyler/geostyler#1746]
# Question

hi there
i see th doc there say "The Symbolizer size (pixels if sizeUnit is not defined)",  i did not set sizeUnit by myself and when i set size to  5（px）,  the image show in openlayer map is extreme big( lile scale 5 times).
is there any chance that the size is mix up with the scale?
![image](https://user-images.githubusercontent.com/63634780/173213307-b2a86683-4b3e-4cb4-892e-e8ab24f74dcd.png)
![image](https://user-images.githubusercontent.com/63634780/173213314-c3358384-7a47-49df-b59b-1e28441e7aff.png)

**Comment by KaiVolland** [comment]
I guess i found the problem: https://github.com/geostyler/geostyler-openlayers-parser/blob/master/src/OlStyleParser.ts#L1073

We're setting `scale` here instead of `size`.

If you like you can provide a pull-request. Otherwise we will fix it sometime. :)

**Comment by KaiVolland** [comment]
Bug is fixed in [#549](https://github.com/geostyler/geostyler-openlayers-parser/pull/549)

**Comment by KaiVolland** [comment]
Once https://github.com/openlayers/openlayers/pull/14364 is release we can adapt the geostyer-openlayers-parser and fix this issue.

**Comment by KaiVolland** [comment]
Fixed with https://github.com/geostyler/geostyler-openlayers-parser/pull/657
