### ISSUE TITLE
Way of maintaining translations up to date

### ISSUE THREAD

**Issue by slafayIGN** [geostyler/geostyler#1751]
# Feature Request

**Is your feature request related to a problem? Please describe.**

As a developer and user of the UI components, I would like a way to make sure that translations of geostyler are all up to date.
At least having an easy way to find missing strings in my language.
At best being warned of missing strings and being helped adding them.

**Describe the solution you'd like**

A new `npm run` command could do that by comparing translation files in any language (`src/locale/*.ts`) with the reference one in english ([src/locale/en_US.ts](https://github.com/geostyler/geostyler/blob/main/src/locale/en_US.ts)).
It would highlight the difference between files.

Suggestion : 

```npm run locale-check --language=fr_FR```
Checks `src/locale/fr_FR.ts` and warns in the console about missing strings or strings that are no longer used (not in the `en_US` file).

```npm run locale-check --language=fr_FR --fix```
Would actually modify the `src/locale/fr_FR.ts` file by adding missing strings (with the same text as in the en_US file) and delete unused strings. Only the actual translation would remain to do.

**Describe alternatives you've considered**

No other idea.

**Additional context**

There are localized strings in other repositories (such as [geostyler/geostyler-demo](https://github.com/geostyler/geostyler-demo)) and the proposal wouldn't check them.

The topic is open for discussion, there isn't any work in progress at the moment.

**Comment by slafayIGN** [comment]
It seems we are synchronized with #1750 :wink:

**Comment by KaiVolland** [comment]
Probably we have some options with TypeScript here. I'm gonna have a look at it.
