### ISSUE TITLE
geostyler-demo doesn't start or build on windows since changes in webpack configuration

### ISSUE THREAD

**Issue by slafayIGN** [geostyler/geostyler#1769]
# Bug

Since recent changes in the way `geostyler-demo` is built, we have troubles making it start. (working on last commit of master branch [91bd6b05](https://github.com/geostyler/geostyler-demo/commit/91bd6b052c637db9dda344a07929de2dd58fe5ae))

* `npm run start` : Webpack takes long minutes building thousands of dependencies and modules in windows environment and never ends. Outputs look like:
```<s> [webpack.Progress] 46% building 2/3 entries 4440/4600 dependencies 426/1374 modules```

* `npm run start`: is ok in a linux environment without `npm link`. It fails when there is a `npm link` in use
* `npm run build` : is not usable in windows environment because it starts with a linux like environment variable definition `NODE_ENV=production`

Also the "troubleshooting" part in [README.md](https://github.com/geostyler/geostyler) is not relevant anymore because there is no `react-scripts` dependency anymore in `geostyler-demo`.

**Desktop:**
 - OS: windows (mostly)
 
 Maybe those webpack changes you are making are still a work in progress. Sorry if this is a bit to soon to submit this issue.

**Comment by KaiVolland** [comment]
You are right. I'll update the README.md and hopefully it will work again on windows.

**Comment by slafayIGN** [comment]
Thank you for the readme update.

Although it doesn't seem to solve this issue on windows.

I think the issue lies in the exclude line in webpack config : https://github.com/geostyler/geostyler-demo/blob/master/config/webpack.common.config.js#L11

**Comment by jansule** [comment]
Thanks for the udpate @slafayIGN. Did you find a workaround for windows?
