### ISSUE TITLE
OSGeoLive 15 Update

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler#1776]
# Docs

### Description:

We have to update the GeoStyler installation on the upcoming OSGeoLive 15. This includes updating docs, install scripts, screenshots, etc.

Following parts have to be updated (probably incomplete):

- https://github.com/OSGeo/OSGeoLive-doc/blob/master/doc/overview/geostyler_overview.rst
- https://github.com/OSGeo/OSGeoLive-doc/blob/master/doc/quickstart/geostyler_quickstart.rst
- https://github.com/OSGeo/OSGeoLive-doc/tree/master/doc/images/projects/geostyler
- https://github.com/OSGeo/OSGeoLive/blob/master/bin/install_geostyler.sh
- transifex

**Comment by jansule** [comment]
Related PRs:

- https://github.com/OSGeo/OSGeoLive-doc/pull/766
- https://github.com/OSGeo/OSGeoLive/pull/337

This issue will be closed as soon as the PRs were merged.

**Comment by KaiVolland** [comment]
@jansule seems like the PRs are merged. Can we close this?

**Comment by jansule** [comment]
I would like to wait until the translations in transifex were also updated. This ticket serves as a reminder to check and apply possible translations. Afterwards I will close this issue.
