### ISSUE TITLE
FilterEditor locale translations

### ISSUE THREAD

**Issue by fperucic** [geostyler/geostyler#1834]
# Bug

**Describe the bug**
FilterEditor strings are not translated, they are hardcoded in english

**To Reproduce**
1. Go to ['Geostyler Demo'](https://geostyler.github.io/geostyler-demo/)
2. Click on 'Edit filter'
3. See error

**Expected behavior**
User should see the translated strings

**Screenshots**
![image](https://user-images.githubusercontent.com/10003528/180751239-ba788c3b-ab33-4846-b3aa-b506ac528ab9.png)

**Comment by jansule** [comment]
Thanks for the info @fperucic. Are you planning on providing a fix for this?

**Comment by fperucic** [comment]
Hi, tried to fix this, but with no luck, due to lack of experience with TypeSript/React.

Fixes to the `FilterTree.tsx` seem easy for my level, since the locale is already there, but I do not where to start with `TextFilterField.tsx` and `AttributeCombo.tsx`

**Comment by jansule** [comment]
Alright, no problem. The general approach for adding locales is as follows:

1. import needed files ([example](https://github.com/geostyler/geostyler/blob/main/src/Component/Symbolizer/Field/ColorField/ColorField.tsx#L43-L45))
2. add `locale` as default prop ([example](https://github.com/geostyler/geostyler/blob/main/src/Component/Symbolizer/Field/ColorField/ColorField.tsx#L50))
3. set default value to english locale ([example](https://github.com/geostyler/geostyler/blob/main/src/Component/Symbolizer/Field/ColorField/ColorField.tsx#L65))
4. add new locales to `locales` type ([example](https://github.com/geostyler/geostyler/blob/main/src/locale/locale.ts))
5. add new locales to i18n files ([example](https://github.com/geostyler/geostyler/blob/main/src/locale/en_US.ts))
6. wrap component into `localize` hoc ([example](https://github.com/geostyler/geostyler/blob/main/src/Component/Symbolizer/Field/ColorField/ColorField.tsx#L120))
7. use locales where needed ([example](https://github.com/geostyler/geostyler/blob/main/src/Component/Symbolizer/Field/ColorField/ColorField.tsx#L105))

It might help to take a look at [ColorField](https://github.com/geostyler/geostyler/blob/main/src/Component/Symbolizer/Field/ColorField/ColorField.tsx), as this component is very lightweight.

**Comment by jansule** [comment]
The different filters themselves will now be translated (kudos to @mholthausen #1866).

![image](https://user-images.githubusercontent.com/12186477/190104452-3144f948-bcce-4691-b6cb-5835502c84c6.png)

What's still missing is a translation for the `Change Filter` text, as well as translations for the input placeholders and error texts.

**Comment by jansule** [comment]
This is still relevant.

**Comment by KaiVolland** [comment]
This is solved with #1866
