### ISSUE TITLE
implement visibility style property to display or hide a specific rule.

### ISSUE THREAD

**Issue by iamgeoknight** [geostyler/geostyler#1940]
# Feature Request
I am currently using geostyler for one of my project. I would like to have **visibility** property implemented in geostyler rules for symbolizers. If **visibility** is true, that symbolizer will be displayed on map. If **visibility** is false, them symbolizer should be hidden.

Something like below:

{
    
    "rules": [               
        {                
            "name": "COASTAL",
            "filter": [
                "==",
                "TYPE",
                "COASTAL"
            ],
            "symbolizers": [
                {
                    "kind": "Line",
                    "color": "#339FFF",
                    "width": 6,
                    "visibility": false
                }                
            ]
        },
        {                
            "name": "MEXICAN",
            "filter": [                
                "==",
                "TYPE",
                "MEXICAN"
            ],
            "symbolizers": [
                {
                    "kind": "Line",
                    "color": "#D4AA2E",
                    "width": 6,
                    "visibility": true
                }
            ]
        },
        {                
            "name": "CANADIAN",
            "filter": [                
                "==",
                "TYPE",
                "CANADIAN"
            ],
            "symbolizers": [
                {
                    "kind": "Line",
                    "color": "#FF5E33",
                    "width": 6,
                    "visibility": true
                }
            ]
        }
    ]
}

**Comment by jansule** [comment]
Thanks @iamgeoknight

+1 from my side.

The geostyler-style already provides that property for symbolizers, so we might only need to add a visibility switch to the UI (and maybe some parsers, where support is still missing). Are you planning on providing a PR for this?

**Comment by miccoh1994** [comment]
@jansule I need this, can I submit a PR? Would be happy to submit change to the openlayers parser repo as well.

**Comment by jansule** [comment]
@miccoh1994 Sure, submitting a PR would be great! Thanks!

**Comment by KaiVolland** [comment]
This is implemented.
