### ISSUE TITLE
GeoStyler freezes when entering "{" in TextSymbolizer

### ISSUE THREAD

**Issue by inaeckert** [geostyler/geostyler#1944]
# Bug

**Describe the bug**
GeoStyler freezes when entering '{' as label in the TextSymbolizer.

**To Reproduce**
1. Open GeoStyler Demo App https://geostyler.github.io/geostyler-demo/
2. Click on the Symbolizer Editor of the rule
3. Select 'Text' as Kind
4. Enter '{' in the text box for the Template
5. Now the app freezes

**Expected behavior**
The text box for the template should show the entered character. The app should be usable afterwards.

**Screenshots**
![image](https://user-images.githubusercontent.com/117343183/199669650-352e4a14-4727-4a0e-8537-661a58c265be.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Firefox

**Comment by jansule** [comment]
Thanks for the info. This bug was fixed in geostyler-sld-parser version 4.0.1 (see https://github.com/geostyler/geostyler-sld-parser/releases/tag/v4.0.1). However, the demo application needs to be updated to include the fix.

**Comment by inaeckert** [comment]
Thank you for your reply! I tried to update the geostyler-sld-parser but I get an error in the build step. The error is similar to this one:
[build](https://github.com/geostyler/geostyler-demo/actions/runs/3325457663/jobs/5498162911) from [pull request](https://github.com/geostyler/geostyler-demo/pull/393)

**Comment by jansule** [comment]
This is probably due to the packages depending on different versions of `geostyler-style`. We are currently working on updating the packages to be compatible with the latest versions. So I'm quite confident that we will provide working versions for geostyler and geostyler-demo within the next days.

**Comment by jansule** [comment]
@inaeckert GeoStyler and depending libraries were updated. So this should work with at least GeoStyler `v10.1.0`. If you still have problems with the build, it might help to take a look at the latest state of GeoStyler Demo (https://github.com/geostyler/geostyler-demo/commit/08abdda4c1db78e09be4757f21de35a55e08b88e).

Feel free to reopen this issue, if the problem still occurs.
