### ISSUE TITLE
CardStyle with empty style throws error

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler#1950]
# Bug

**Describe the bug**

When trying to edit a Rule of a `<CardStyle />` where the optional `style` property was not specified, a `TypeError: Cannot read properties of undefined (reading 'symbolizers')` will be thrown.

**To Reproduce**
1. Go to https://geostyler.github.io/geostyler/latest/index.html#!/Components/CardStyle/CardStyle/CardStyle/1
2. Click on 'VIEW CODE' below the example component
3. Remove line `style={style}` from `<CardStyle />`
4. Click on 'ADD' below the rules section
5. Click on the newly added rule
6. See thrown error

**Expected behavior**

No error should be thrown. Instead, an empty rule should be visible/editable.

**Screenshots**

![geostyler-card-layout-bug](https://user-images.githubusercontent.com/12186477/201147992-4bd80f3b-7c4a-4014-875c-511ea968650c.gif)

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser any
 - Version any

**Additional context**
None

**Comment by KaiVolland** [comment]
@jansule is this solved?

**Comment by KaiVolland** [comment]
I can't reproduce this. Please check again and close if fixed.
