### ISSUE TITLE
Locale Wrapper uses legacy Context API

### ISSUE THREAD

**Issue by KaiVolland** [geostyler/geostyler#1971]
The LocaleWrapper uses the legacy Context API of react. This needs to be transformed to the new Context API.

**Comment by KaiVolland** [comment]
… actually the Context used here is imported from antd. Not sure how to deal with this.

**Comment by jansule** [comment]
@KaiVolland is this still an open issue?

**Comment by KaiVolland** [comment]
It is superseeded by #2171
