### ISSUE TITLE
Add info about semantic release and commit messages

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler#1999]
# Docs

### Description:

We should add infos about the expected commit message format to README.md and CONTRIBUTING.md in order to lower the barrier for contributors

**Comment by slafayIGN** [comment]
Sorry for not respecting the commit  naming convention in #1997 , first time I bump into it, and I didn't see the failing commitlint before opening the merge request.

**Comment by jansule** [comment]
No worries. That's exactly why we should add this info to our documentation. We set the settings of commitlint to only print a warning, since we can always adjust the commit message before merging.
