### ISSUE TITLE
Problems with filter on string attributes

### ISSUE THREAD

**Issue by inaec** [geostyler/geostyler#2008]
# Bug

**Describe the bug**
I created a rule with a filter on a string attribute with the GeoStyler demo app. The generated sld file contains line breaks in the elements for the PropertyName and the Literal:

```
<Filter>
  <PropertyIsEqualTo>
    <PropertyName>
      name
    </PropertyName>
    <Literal>
      point_0
    </Literal>
  </PropertyIsEqualTo>
</Filter>
```

Then I applied this style to a layer in the GeoServer and the filter didn't work. No features are visible.
I also checked a layer in QGis. But the same happens here. No features are visible. 
When I remove the line breaks from the sld file, it works in QGis and in the GeoServer. So this filter works:

```
<Filter>
  <PropertyIsEqualTo>
    <PropertyName>name</PropertyName>
    <Literal>point_0</Literal>
  </PropertyIsEqualTo>
</Filter>
```

**To Reproduce**
1. Create a rule in the GeoStyler with a PropertyIsEqualTo-filter on a string attribute.
2. Create a layer in QGis or GeoServer with at least one feature matching the filter created in step 1.
3. Apply the sld file from the GeoStyler to the layer in QGis or GeoServer.
4. Look at the layer. The features matching the filter in the sld file are not visible.
5. Remove the line breaks from the sld file and apply the style again. The features matching the filter in the sld file are visible.

**Expected behavior**
Sld files with a filter on a string attribute should work in GeoServer and QGis. In fact, it might also be an issue in these apps. I created this issue because both apps have problems with the line breaks.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Firefox
 - GeoServer: 2.22.0
 - QGis: 3.16.12

**Comment by KaiVolland** [comment]
Thanks for reporting the issue.
This seems to be a problem related to the `geostyler-sld-parser`.

We're using the `builderOptions: {
      format: true
    }` in the Demo.

Im not sure how whitespaces and newlines should be handled correctly within a xml. Maybe we have to remove the format option from the demo.
