### ISSUE TITLE
Classification not working on certain attributes

### ISSUE THREAD

**Issue by inaeckert** [geostyler/geostyler#2012]
# Bug

**Describe the bug**
Classification seems to have some problems with attributes containing special characters ('[' and ']' in my case).

**To Reproduce**
1. Load some data to the geostyler demo app with attribute names containing '[' and ']'. You can use this file for testing 
[sample_spec_char.zip](https://github.com/geostyler/geostyler/files/10192246/sample_spec_char.zip) . It contains features with attribute name "distance [m]".
2. Click on Classification, select the attribute with the special character, select any classification method and press Classify.
3. The intervals in the generated rules are not correct:
![image](https://user-images.githubusercontent.com/117343183/206637556-52b63d41-4f06-4467-81fc-f0b25ca2a1ad.png)

**Expected behavior**
Classification on attributes with '[' and ']' should work.

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser Chrome, Firefox

**Comment by KaiVolland** [comment]
Thanks for the report.

We are using lodash `_get` to extract the values here: https://github.com/geostyler/geostyler/blob/main/src/Util/RuleGeneratorUtil.ts#L72

This could be the problem and think we could transform it to some smarter typescript code which would be more flexible.

@inaeckert Do you think you could provide a PR to fix this?

**Comment by inaeckert** [comment]
Hi, thank you for your answer and sorry for my late reply. Unfortunately, I don't have time right now to get more familiar with ts and the geostyler and fix this issue. Maybe in a few months.

**Comment by KaiVolland** [comment]
Fixed with #2054.
