### ISSUE TITLE
How to set locale of Style control

### ISSUE THREAD

**Issue by AlenKelemen** [geostyler/geostyler#2110]
# How to set locale property of all controls which are part of Style control

Currently, for Style control there is:
```
Style: {
    addRuleBtnText: 'Add Rule',
    cloneRulesBtnText: 'Clone Rules',
    removeRulesBtnText: 'Remove Rules',
    nameFieldLabel: 'Name',
    nameFieldPlaceholder: 'Enter Name',
    titleFieldLabel: 'Title',
    titleFieldPlaceholder: 'Enter Title',
    colorLabel: 'Select color',
    radiusLabel: 'Select radius',
    opacityLabel: 'Select opacity',
    symbolLabel: 'Select symbol',
    multiEditLabel: 'Multi edit',
    ruleGeneratorWindowBtnText: 'Classification'
}
```
but Style incorporates other controls like Rule and markEditor how to set their locale property ?
Is it possible to reference them ?

**Comment by KaiVolland** [comment]
Hey, you can wrap the UI components with a config provider from antd to provide custom labels.

You could use https://github.com/geostyler/geostyler/blob/main/src/locale/en_US.ts as a starting point at extend or replace the strings you want. If you are using typescript you can even use the `GeoStylerLocale` type to make things easier https://github.com/geostyler/geostyler/blob/main/src/locale/locale.ts

Have a look at the geostyler demo code https://github.com/geostyler/geostyler-demo/blob/master/src/App.tsx#L253.

I hope this helps.

**Comment by AlenKelemen** [comment]
Got it, thanks,
so proper way would be to create locale for my language and use it with <ConfigProvider locale ...

**Comment by jansule** [comment]
> so proper way would be to create locale for my language and use it with <ConfigProvider locale ...

Yes, this would be the way to go. We are also interested in supporting additional languages, so if you are planning on adding a new language, you are more than welcome to add the translation file to https://github.com/geostyler/geostyler/tree/main/src/locale and open a PR for this.

**Comment by AlenKelemen** [comment]
:+1:

**Comment by AlenKelemen** [comment]
I had success with the following:

```
import { wanted-geostyler - compoment, locale as GsLocale} from 'geostyler';
import ConfigProvider from 'antd/lib/config-provider'

//... my component code
render() {
    return (
        <ConfigProvider locale={GsLocale.fr_FR}>
            <wanted-geostyler-component
                foo=""
                bar={ }
            />
        </ConfigProvider>
    );
}
```
If you think it is regular way to set locale, I suggests it would be useful to append it to documentation somewhere.

**Comment by jansule** [comment]
Yes, this looks like the proper way to set locales. I agree on you with adding this information to the docs. We are currently updating the approach a little by providing a custom context for all static geostyler configs. As soon as this is done, we will update the docs accordingly.

I will add this issue to the TODO list of our upcoming code sprint, which will take place next month (08.-12.05, see https://geostyler.org/). There are also still a few open spots for the code sprint, in case you are interested in participating :smile:

**Comment by AlenKelemen** [comment]
https://github.com/geostyler/geostyler/pull/2115

**Comment by jansule** [comment]
Thanks for providing the PR! Is it ok, if we ping you, when there will be new snippets to be translated in the future?

**Comment by AlenKelemen** [comment]
:+1: 
Of course, no problem...

**Comment by KaiVolland** [comment]
I guess this one can be closed. Thanks for contributing @AlenKelemen
