### ISSUE TITLE
Move Remove Symbolizer Button to Tablist in Symbolizer Window

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler#2149]
# Feature Request

**Is your feature request related to a problem? Please describe.**

The "Add Symbolizer" button is currently on the top row next to the tab list of symbolizers. The "Remove Symbolizer" button, however, is at the bottom of the input fields, which is often not directly visible and users have to scroll to find it.

**Describe the solution you'd like**

I think we should move the "Remove Symbolizer" button from to bottom to the actual tab item (just like it is done with browser tabs).

![image](https://github.com/geostyler/geostyler/assets/12186477/b6312387-c006-4010-ba85-e03889362048)

**Describe alternatives you've considered**

**Additional context**

**Comment by KaiVolland** [comment]
Maybe we could also add an extra Tab with a **+** instead of the add button.
