### ISSUE TITLE
Problem with fields Opacity and Fill-Opacity and PreviewMap

### ISSUE THREAD

**Issue by jdonlucas** [geostyler/geostyler#2215]
### Description

When loading a wfs layer and using the Symbolizer editor there are two fields: `fill-opacity` and `opacity`. Changing the `fill-opacity` field doesn't change the layer in the PreviewMap but it does changes the SLD code adding the `fill-opacity` parameter. And if one changes the `opacity` field the layer opacity changes in the PreviewMap but it does nothing to the SLD code. Also, by changing `stroke-opacity` resets the field `opacity` which is a bit annoying.

### Expected behaviour

I suppose that the field `fill-opacity` should change the opacity of the layer in the PreviewMap. I don't know if the `opacity` field is needed in this case.

### How to reproduce

 I tested this on the geostyler demo. Here is a video of the problem:

[geostyler-fill-opacity-issue.webm](https://github.com/geostyler/geostyler/assets/52864142/d582da73-4722-4fe9-ba85-a32e2093d9ac)

This is the wfs that I'm using in the example:

     url: https://artf.centrogeo.org.mx/geoserver/ows
     FeatureTypeName: geonode:mun_20_oax_8fc15089c45e7415a7d864a7f65c885c

**Comment by KaiVolland** [comment]
Hey Jaime, this is a problem we have right from the beginning of the project. Especially in the combination of openlayers (previewmap) and SLD.

- [SLD does not support general opacity of a symbolizer](https://github.com/geostyler/geostyler-sld-parser/blob/master/src/SldStyleParser.ts#L125) 
- [OpenLayers does not support fill opacity](https://github.com/geostyler/geostyler-openlayers-parser/blob/master/src/OlStyleParser.ts#L79)

So actually this is mainly a problem in communication/notification. And i can completly understand why this is confusing and annoying in the demo.

Actually there should be an exclamation mark at the opacity field when the SLD Parser is selected. I'll open an issue for this an will close this one.

**Comment by jdonlucas** [comment]
I see, what if the SLD parser can interpret the opacity as the fill-opacity and stroke-opacity, in that way if someone parse a style in the OpenLayers format it copies the value of the opacity into both fields unless stroke opacity is set. And for the symbolizer editor, what is the use of the 2 fields, I mean fill-opacity and opacity? Is there a case where both of them are used at the same time or is because of this incompatibility of SLD - OL?

Just asking this out of curiosity, to better understand the issue, I'm happy to help if there's something I can do
