### ISSUE TITLE
Nominal classification

### ISSUE THREAD

**Issue by inaec** [geostyler/geostyler#2347]
### Description

Nominal classification is missing the rule for value 0.

### Expected behaviour

When the uploaded data has features with attribute value 0, a corresponding rule should be created.

### How to reproduce

1. Change to CardLayout in GeoStyler Demo App

2. Upload sample data in GeoStyler Demo App containing features with attribute values 0, e.g. 
[sample.zip](https://github.com/geostyler/geostyler/files/12461701/sample.zip)

3. Go to 'Classification', select attribute 'value' and 'Nominal' as Level of Measurement. Select 3 Number of Classes. Select 'Classify'.
4. Two rules are now created:
![image](https://github.com/geostyler/geostyler/assets/117343183/d7224485-a785-4230-b9cd-93a4c3e9444b)

Expected behaviour: 3 rules

**Comment by KaiVolland** [comment]
Thanks for the report. We'll have a look at it.
