### ISSUE TITLE
Possible to add a rule based on comparison between columns?

### ISSUE THREAD

**Issue by pelord** [geostyler/geostyler#2376]
### Question

Is it possible to set a filter based on comparison between 2 properties

In this case, I try to style data based on a parent child relationship.
The base style for parent is a blue dot
The childs are not shown until a parent is clicked. 

When I click on the parent, I set for every feature, the property _effectiveCondition  based on the parent id. 
Then, I want to style the childs based on the clicked parent.. 
```
      "filter": [
        "==",
        "_effectiveCondition",
        {{fieldContainingTheConditionToBeMet}}
      ]
```

**Comment by jansule** [comment]
I'm not quite sure, I correctly understand what you are intending to do. Could you provide a minimal code sample or even some pseudo-code so that it becomes clearer to me?

**Comment by pelord** [comment]
Here the initial state:
![image](https://github.com/geostyler/geostyler/assets/7397743/2deb3f4e-7aac-4ba9-8207-3f7f07b1e2ff)

If I click on one of these features, I set the column "valueToBeSetDuringAClickAction" with the content of the clicked feature (column value).

Here if i click on the feature with id =2

![image](https://github.com/geostyler/geostyler/assets/7397743/be4a82e3-6e8d-4350-aab4-a48a7d9ac1e0)


Here my question: Is it possible to filter values based on 2 columns, returning a true/false logic?

      "filter": [
        "==",
        "value",
        {{valueToBeSetDuringAClickAction}}
      ]

**Comment by jansule** [comment]
Thanks for providing more info @pelord.

So for the case you mentioned, you would like to compare the value of column `value` and the value of column `valueToBeSetDuringAClickAction`, right? So this would only return true for the row where id is 2.

This should be possible with following filter:

```
"filter": [
        "==",
        {
            "name": "property",
            "args": [
                "value"
            ]
        },
        {
            "name": "property",
            "args": [
                "valueToBeSetDuringAClickAction"
            ]
        }
    ],
```
Following PR and related issue might be interesting for you in that case: https://github.com/geostyler/geostyler-openlayers-parser/pull/794 https://github.com/geostyler/geostyler-openlayers-parser/issues/791

**Comment by jansule** [comment]
Please note that the UI cannot handle this currently. Also support for the different parsers might vary as well.

**Comment by pelord** [comment]
I will give a try to your exemple soon! 
Thanks! You make my year 😀

**Comment by KaiVolland** [comment]
It seems like this issues could haven been solved. If I'm wrong please reopen or comment @pelord .
