### ISSUE TITLE
Support fonts as symbols for points

### ISSUE THREAD

**Issue by marcjansen** [geostyler/geostyler#243]
It'd be nice if we could use fonts as source for the symbol to use for a point feature.

**Comment by jansule** [comment]
The initial setup exists via #428. Component TextEditor is able to set static text to all features that match a rule. What's still missing is the proper integration of different fonts such as font-awesome to enable icon fonts, which I guess is a crucial part.

**Comment by weskamm** [comment]
Diving into this now

**Comment by jansule** [comment]
@weskamm did you gain any insights that are worth sharing here?

**Comment by KaiVolland** [comment]
https://github.com/geostyler/geostyler-openlayers-parser/pull/231
