### ISSUE TITLE
Remove Unused Properties in Rules Component

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler#2466]
`<Rules>` provides two properties `showAmount`, `showDuplicates` which are not being used by the component anymore (now handled via composition context). These should be removed. Since this introduces a breaking change, we should wait for the code sprint to do so.

 https://github.com/geostyler/geostyler/blob/141238038a867f0f59aad1b8208093a7279997bb/src/Component/Rules/Rules.tsx#L63-L67

**Comment by KaiVolland** [comment]
@jansule can you clarify this? The current state is that these still live in the [`RulesInternalProps`](https://github.com/geostyler/geostyler/blob/141238038a867f0f59aad1b8208093a7279997bb/src/Component/Rules/Rules.tsx#L62). I can't find a related config in the composition context and i guess they should just be moved inside the component from [`RulesInternalProps`](https://github.com/geostyler/geostyler/blob/141238038a867f0f59aad1b8208093a7279997bb/src/Component/Rules/Rules.tsx#L62) to [`RulesComposableProps`](https://github.com/geostyler/geostyler/blob/141238038a867f0f59aad1b8208093a7279997bb/src/Component/Rules/Rules.tsx#L58) right?

**Comment by jansule** [comment]
No they should be removed. There is no occurrence of the props, since we can configure it for the RuleCard via composition.
