### ISSUE TITLE
Issue of the ColorPicker

### ISSUE THREAD

**Issue by TreffN** [geostyler/geostyler#2501]
### Description

Hello,
When integrating the GeoStyler to manipulate the style of drawing tools, the transfer of the fill colour does not work as expected.
After changing the colour, an rgb value is displayed in the colour bar, which is also returned, instead of a hex value. In addition, the bar for changing the transparency (alpha value) is available in the colour picker.
The same behaviour occurs with the stroke colour, but here the transfer of the colour works.
Ant version 5.21.2 is used in the project.

### Expected behaviour

Chosen color in the ColorPicker should be displayed correctly for each drawn feature and the transparency bar should not be visible

### How to reproduce

Include GeoStyler in a project with ant-version 5.21.2

**Comment by KaiVolland** [comment]
I'll have a look at it.
