### ISSUE TITLE
Handling of invalid inputs in CodeEditor

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler#359]
The CodeEditor allows to enter/edit/remove any property of a geostyler-style. When using the geostyler-style there, no parser is plugged in in-between that might catch an invalid input. This might lead to unexpected behaviour and/or crashing of the geostyler. 

For instance, the property `symbolizer` of a `rule` is defined as required in geostyler-style. Thus, geostyler assumes that this property exists (at least as empty array). However, it is possible to remove this property in the CodeEditor which crashes the geostyler.

Should we handle this problem somehow? And if so, how should we do this?

**Comment by marcjansen** [comment]
is this fixed with the commit elsewhere?

**Comment by jansule** [comment]
No, not yet. There is still the question of how to handle this problem.

**Comment by KaiVolland** [comment]
I think this is covered by the new CodeEditor introduced with https://github.com/geostyler/geostyler/pull/1395. Please reopen if you think this is still an issue.
