### ISSUE TITLE
GeoStyler Demo and StyleGuide don't work in older browsers, e.g. IE11

### ISSUE THREAD

**Issue by ahennr** [geostyler/geostyler#642]

**Comment by marcjansen** [comment]
#641 is merged now, can we close this issue?

**Comment by KaiVolland** [comment]
@marcjansen I think #641 only fixes the browser build. Not the Demo or StyleGuide.
IMHO we shouldn't put to much effort in making the API and Demo work in outdated Browsers.

**Comment by marcjansen** [comment]
I agree. How much work would it be? If we are talking about polyfills, then this cannot be much, right?

**Comment by KaiVolland** [comment]
@ahennr do you think we can close this issue?

**Comment by ahennr** [comment]
GeoStyler Demo still isn't working in IE11 currently. I would try to solve this e.g. via polyfills (timeboxed, f.e. 1h). If it is not easy to solve, we could still decide not to support outdated browsers. What do you think @KaiVolland @marcjansen

**Comment by KaiVolland** [comment]
Mir persönlich ist egal, ob der GeoStyler im IE 11 läuft oder nicht. Schaden tut es aber mit Sicherheit nicht. Also von mir aus gern.

**Comment by KaiVolland** [comment]
GeoStyler does not officially support IE as discussed in the july monthly: https://github.com/geostyler/geostyler/discussions/1464
