### ISSUE TITLE
Overhaul GeoStyler

### ISSUE THREAD

**Issue by KaiVolland** [geostyler/geostyler#650]
@jansule and @KaiVolland talked about an overhaul of the component concept.

Currently the user of a component is stuck to its child components, or has to pass properties via an ObjectProperty like `sldRendererProps` in the `Style` component. This feels a bit hackish and doesn't fit the approach of React.

An alternative approach would be to work with renderers:

```jsx
<Style
  style={style}
  nameRenderer={<SpecialStyleNamefield  onChange={/*TODO*/} />}
  rulesRenderer={
    <RuleTable
      onChange={/*TODO*/} 
      ruleRenderer={
        <Rule
          onChange={/*TODO*/} 
          nameRenderer={<NameSpecial onChange={/*TODO*/} />}
          symbolizersRenderer={<SpecialSymbolizersRenderer onChange={/*TODO*/} />}
          filterRenderer={undefined} // Use default FilterRenderer
          scaleDenominatorRenderer={false} // Will not be shown
        />
      }
    />
  }
/>
```

### Paradigms:
1. A component would have a renderer for its (main) child components.
2. If you don't specifiy a renderer (or undefined) a default component is used instead.
3. If you provide `false` nothing will be renderer.

### Open Questions:

1. How to handle the changeListeners and its default behaviour?

Please share your thoughts!

**Comment by KaiVolland** [comment]
With #1179 we show an approach to customize the fields of an Editor:

The `fieldConfig` property allows to replace or hide single Fields of an Editor.

It doesn't allow to change the order of the Elements of an Editor, which might be achieved with a children-based approach. The disadvantag of the childre-based approach would that you'd have to add every field even if no change is needed.

**Comment by jansule** [comment]
See also #1186 for another approach to customize fields. There, react's context feature was used.
This allows the customisation for all customisable components from a global point. The big advantage here is that no props have to be propagated through all parent components. So each component checks for itself if it should be customised. This should avoid errors and keep the code clean. Also, if no provider is being used, the component falls back to its default state.
