### ISSUE TITLE
Filter Encoding as seperate parser implementation

### ISSUE THREAD

**Issue by chrismayer** [geostyler/geostyler#930]
### Description:

I just wanted to discuss if it would make sense to put the OGC Filter Encoding (FE) part from the SLD parser to a separate parser implementation / repository.
Thus the filter encoding stuff could be used more easily in projects, where only filtering of layers and data is taken into account. The rest of the SLD overhead could then be skipped easily.

What do you thinks @terrestris/devs and of course anyone else, who has an opinion on this.

**Comment by hwbllmnn** [comment]
That makes a lot of sense to me, especially since we already have a separate CQL parser implementation at https://github.com/terrestris/geostyler-cql-parser/ as well.
