### ISSUE TITLE
CookBook, Tutorials, etc

### ISSUE THREAD

**Issue by KaiVolland** [geostyler/geostyler#988]
To clarify the use of the `GeoStyler` as a library we should develop some kind of `CookBook`. Comparable to [the one of the `Geoserver`](https://docs.geoserver.org/stable/en/user/styling/sld/cookbook/).

Another way to increase the popularity could be some tutorials or blogposts with "real world" examples.

**Comment by KaiVolland** [comment]
Possible examples for tutorials:

- Simple:
  - A fill color for every Bundesland (or color Wahlkreis of european election by winner party)
  - Bundesliga Stadium location with symbol of the team @chrismayer your turn :smile:

- Complex:
  - Road symbolization with complex symbolizers for different types of roads (Autobahn, streets, pedestrian…)
  - Itineraries map with styles for polygons, points and lines. eg:
![https://d3dqioy2sca31t.cloudfront.net/Projects/cms/production/000/016/909/original/13f5df138e1249eb786248c0f787eb31/ireland-itinerary.jpg](https://d3dqioy2sca31t.cloudfront.net/Projects/cms/production/000/016/909/original/13f5df138e1249eb786248c0f787eb31/ireland-itinerary.jpg)

**Comment by jansule** [comment]
Together with @KaiVolland and @dnlkoch we decided to add all examples in the SLD cookbook to the examples popup in the geostyler-demo. Also the examples button should be highlighted (e.g. via https://introjs.com/)

**Comment by jansule** [comment]
The creation of geostlyer workshops was moved into seperate issues: https://github.com/terrestris/geostyler/issues/1196 https://github.com/terrestris/geostyler/issues/1197

**Comment by krishnaglodha** [comment]
Hi @jansule , I would be interested in this ticket

**Comment by jansule** [comment]
That's great @krishnaglodha!

Regarding the tools to use, we had good experiences with using [jekyll](https://jekyllrb.com/) as a static site generator (as it integrates nicely with github pages). There is also a [gitbook theme](http://jekyllthemes.org/themes/gitbook/) that can be used.

Please let us know, if we should create an empty repository on the GeoStyler organization for the cookbook.

**Comment by krishnaglodha** [comment]
Hi, I'm checking https://jekyllrb.com/, I'll install on local , meanwhile you can create an empty repository, and we can get on quick call to discuss structure
