### ISSUE TITLE
Usage of base64/datauri Icons

### ISSUE THREAD

**Issue by KaiVolland** [geostyler/geostyler#989]
## FEATUREREQUEST

We should add base64/datauri support for the used icons. Currently only urls work properly. This most likely will affect all parsers.

**Comment by annarieger** [comment]
`base64` icons are already supported from `geostyler-openalyers-parser` and works well in current version.

Support for SLD is basically possible by using of `InlineContent` tag inside of `ExternalGraphic` which replaces `OnlineResource` for usual image resources. 
While using `InlineContent` the `se` namespace must be bound into SLD, so the style will look something like 
```
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns="http://www.opengis.net/sld"
    xmlns:sld="http://www.opengis.net/sld"
    xmlns:se="http://www.opengis.net/se"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd
                        http://www.opengis.net/se http://schemas.opengis.net/se/1.1.0/FeatureStyle.xsd"
    version="1.1.0"
    >
    <UserLayer>
      <se:Name>sld-renderer-style</se:Name>
        <UserStyle>
            <se:FeatureTypeStyle>
                <se:Rule>
                  <se:Name>sld-renderer-rule-1</se:Name>
                    <se:LineSymbolizer>
                        <se:Stroke>
                            <se:GraphicStroke>
                                <se:Graphic>
                                    <se:ExternalGraphic>
                                        <se:InlineContent encoding="base64">iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAK3RFWHRDcmVhdGlvbiBUaW1lAFd0IDE0IHdyeiAyMDEwIDEyOjA2OjAyICswMTAweoAlkgAAAAd0SU1FB9oJDgo6HdmGt90AAAAJcEhZcwAACxIAAAsSAdLdfvwAAAAEZ0FNQQAAsY8L/GEFAAABfklEQVR42mP8//8/AwYACn779o2bmxtTiokBG9iwboOfq9+1K9eI0vDp06cZk2e8ffp2zuQ5mPZj0bB963aGLwxTI6YdO3QMiyX/UcHz58/tLeyXZ674O+NfgVthWnTaz58/kRWg27B8yXKu31yeGp6MjIwpVimnjp86fvg4Tic9ffp0zfI1ZU7lfBx8QK6WpFasSdzMiTN//fqFRQPQusULFsvzyFsqWMIFw4zDHt5+uH/Xfiwarl27tnj+4nSzdDYWNrigtIB0iF5IZ1MnMOhQNACNnztjrq64roWiJQMqCDUO+/D6w/YN21E0XLp06fD+w3l2+cjGwy1Jt82YO3Pe+/fvoRqAfupq6bKVs7VQsMAa8REmEf8+/V04fSFUw/Hjxy+cvZBklgwMSqwagIGWYpm6cOEiYDCyAI2fPnG6mrD6n39/Lj25xIADAB325/vvVQtXsXz58uX7z+8vfr7I2ZrNgBew87HfvnebERg+X79+/ffvHwMRgJWVFQBa4Mt756r78AAAAABJRU5ErkJggg==</se:InlineContent>
                                        <se:Format>image/jpeg</se:Format>
                                    </se:ExternalGraphic>
                                </se:Graphic>
                            </se:GraphicStroke>
                        </se:Stroke>
                    </se:LineSymbolizer>
                </se:Rule>
            </se:FeatureTypeStyle>
        </UserStyle>
    </UserLayer>
</StyledLayerDescriptor>
```

On the other hand, using of namespaces leads to big code refactoring (e.g. style name or rule name parsing must be adapted since the appropriate field name will be changed from `<Name>` to `<se:Name>`).

 It should be discussed once again if the effort of this feature is worthwhile.

**Comment by hwbllmnn** [comment]
Perhaps you can get around that by adding `xmlns="http://www.opengis.net/se"` on the `FeatureTypeStyle` element.

**Comment by elanioazul** [comment]
Hi,

I am trying to make use of base64 encoded incons but I got the following error in browser when transforming from sld to OL styles for a point vector tile layer:
ERROR Error: Uncaught (in promise): TypeError: Cannot read property '$' of undefined
TypeError: Cannot read property '$' of undefined
    at SldStyleParser.push../node_modules/geostyler-sld-parser/build/dist/SldStyleParser.js.SldStyleParser.getIconSymbolizerFromSldSymbolizer (SldStyleParser.js:561)
    at SldStyleParser.push../node_modules/geostyler-sld-parser/build/dist/SldStyleParser.js.SldStyleParser.getPointSymbolizerFromSldSymbolizer (SldStyleParser.js:590)
    at SldStyleParser.js:999
    at Array.forEach (<anonymous>)
    at SldStyleParser.js:995
    at Array.forEach (<anonymous>)
    at SldStyleParser.push../node_modules/geostyler-sld-parser/build/dist/SldStyleParser.js.SldStyleParser.getSymbolizersFromRule (SldStyleParser.js:994)

Above it is pointed out that base64 icons are already supported but
-My intent failed
-I have copied the example given by annarieger on 29May2019 and setup a geoserver style and tried to layer preview a point and line layers in Geoserver using it.  None of the layers are displayed with it, tough the icon is a fancy pinck triangle. 

Am I doing something wrong?
Is it base64 icons really implemented in the code? I look for the keyword "InlineContent" in the code and I find nothing.

Thx!
Greetings

**Comment by jansule** [comment]
I think there might have been a misunderstanding. The sentence in https://github.com/geostyler/geostyler/issues/989#issuecomment-496902398

> Support for SLD is basically possible by using of InlineContent tag inside of ExternalGraphic which replaces OnlineResource for usual image resources.

refers only to how base64 encoded icons can be handled in SLD in general.

The geostyler-sld-parser does not (yet?) provide this feature.

Please correct me, if I'm wrong @annarieger @KaiVolland

**Comment by annarieger** [comment]
You're right, @jansule. The related pull request (https://github.com/geostyler/geostyler-sld-parser/pull/217) which should enable this functionality is still wip and needs some love so the changes were not integrated into geostyler.

**Comment by olivierdalang** [comment]
I'm working on implementing this on QGIS (see https://github.com/qgis/QGIS/pull/61749). It would be really nice to support this here too :-)

@jansule @KaiVolland Can we reopen this issue ?

For what it's worth, it's currently possible to partially workaround this issue for the web/openlayers by using data uri in an OnlineResource, but it doesn't work on geoserver.

```
<se:ExternalGraphic>
    <se:OnlineResource xlink:type="simple" xlink:href="data:;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=="/>
    <se:Format>application/octet-stream</se:Format>
</se:ExternalGraphic>
```

It's the same situation for SLDReader, see the feature request on their tracker [NieuwlandGeo/SLDReader#198](https://github.com/NieuwlandGeo/SLDReader/issues/198)

**Comment by jansule** [comment]
Sure, reopened it
